---
# - name: Linux Init 
  # import_playbook: ../init_linux_instance/linux_init.yml

- name: Set up KVM infrastructure
  hosts: virt_hosts
  become: true
  vars:
    create_nat_network: true
  roles:
  - ../../roles/kvm