---
- name: Create and Install Bastion Server
  hosts: localhost
  become: yes
  vars:
    vm_name: ocp-bastion-server
    vm_ram: 4096
    vm_vcpus: 2
    vm_disk_path: /var/lib/libvirt/images/ocp-bastion-server.qcow2
    vm_disk_size: 20G
    vm_network: openshift4
    vm_root_password: password
    vm_os_variant: rhel8.0

  tasks:
    - name: Create VM disk using virt-builder
      command: >
        virt-builder alma-8.5
        --format qcow2
        --size {{ vm_disk_size }}
        -o {{ vm_disk_path }}
        --root-password password:{{ vm_root_password }}
      args:
        creates: "{{ vm_disk_path }}"

    - name: Install VM using virt-install
      command: >
        virt-install
        --name {{ vm_name }}
        --ram {{ vm_ram }}
        --vcpus {{ vm_vcpus }}
        --disk path={{ vm_disk_path }}
        --os-type linux
        --os-variant {{ vm_os_variant }}
        --network bridge={{ vm_network }}
        --graphics none
        --serial pty
        --console pty
        --boot hd
        --import
      args:
        creates: "/etc/libvirt/qemu/{{ vm_name }}.xml"