---
# tasks file for kvm

- name: Check for cpu virtualization support
  shell: grep -E 'vmx|svm' /proc/cpuinfo
  register: virt_extensions
  failed_when: virt_extensions.rc != 0
  changed_when: false

- name: Install KVM and related packages
  package:
    name: "{{ kvm_packages }}"
    state: present

- name: Check if KVM modules are loaded
  shell: lsmod | grep -i kvm
  register: kvm_modules
  failed_when: kvm_modules.rc != 0
  changed_when: false

- name: Enable and start kvm services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - cockpit.socket
  - libvirtd
