---
# Example playbook for deploying HAProxy load balancer for OpenShift

- name: Deploy HAProxy Load Balancer for OpenShift
  hosts: loadbalancer
  become: true
  
  vars:
    # OpenShift cluster settings
    openshift:
      cluster_name: ocp4
      domain: example.com
    
    # Bootstrap node
    bootstrap_node:
      name: bootstrap
      ip: 192.168.100.10
    
    # Master nodes
    master_nodes:
      - name: master01
        ip: 192.168.100.11
      - name: master02
        ip: 192.168.100.12
      - name: master03
        ip: 192.168.100.13
    
    # Worker nodes
    worker_nodes:
      - name: worker01
        ip: 192.168.100.21
      - name: worker02
        ip: 192.168.100.22
      - name: worker03
        ip: 192.168.100.23
    
    # SELinux ports to allow HAProxy to use
    selinux_ports:
      - port: 6443
        proto: tcp
      - port: 22623
        proto: tcp
      - port: 32700
        proto: tcp
    
    # Firewall services and ports to open
    firewall_services:
      - http
      - https
    
    firewall_ports:
      - port: 6443
        proto: tcp
      - port: 22623
        proto: tcp
  
  roles:
    - haproxy_lb
  
  post_tasks:
    - name: Verify HAProxy is running
      ansible.builtin.systemd:
        name: haproxy
        state: started
      register: haproxy_status
    
    - name: Display HAProxy status
      ansible.builtin.debug:
        msg: "HAProxy is {{ 'running' if haproxy_status.status.ActiveState == 'active' else 'not running' }}"
    
    - name: Test HAProxy Kubernetes API endpoint
      ansible.builtin.uri:
        url: "https://api.{{ openshift.cluster_name }}.{{ openshift.domain }}:6443/healthz"
        method: GET
        validate_certs: no
        status_code: [200, 403, 404, 500, 503]
      register: api_test
      ignore_errors: yes
    
    - name: Display HAProxy API test results
      ansible.builtin.debug:
        msg: >
          API endpoint test status: {{ api_test.status }} 
          (Note: A 503 Service Unavailable is expected if the OpenShift cluster is not yet installed)
    
    - name: Set message of the day for load balancer host
      ansible.builtin.copy:
        content: |
          ****************************************************************
          *                                                              *
          *  OpenShift Container Platform 4 Load Balancer                *
          *                                                              *
          *  HAProxy is configured for the following services:           *
          *  - Kubernetes API: api.{{ openshift.cluster_name }}.{{ openshift.domain }}:6443       *
          *  - Machine Config: api-int.{{ openshift.cluster_name }}.{{ openshift.domain }}:22623  *
          *  - HTTP Router: *.apps.{{ openshift.cluster_name }}.{{ openshift.domain }}:80         *
          *  - HTTPS Router: *.apps.{{ openshift.cluster_name }}.{{ openshift.domain }}:443       *
          *                                                              *
          ****************************************************************
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'