---
- name: Converge
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    gitlab_external_url: https://localhost
    cert_ca_cert_src: ./certs/ca.crt
    cert_ca_key_src: ./certs/ca.key
    cert_ca_conf_src: ./certs/cert.conf
    cert_ca_cert_name: mycompany
    cert_dest_directory: /etc/ssl
    cert_name: gitlab
    cert_owner: gitlab
    cert_group: gitlab
  pre_tasks:
    - name: Create gitlab user
      user:
        name: gitlab
        state: present
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - activatedinc.sslcert
    - ansible-role-gitlab
