---
domain: skylarhoughtongithub.com
default_password: "{{ lookup('amazon.aws.aws_ssm', '/kvm/vm_root_password', region='us-east-2' )}}"
default_ssh_public_key: "{{ lookup('amazon.aws.aws_ssm', '/kvm/vm_root_pub_key', region='us-east-2' )}}"

bridge_configuration:
  create: true
  name: br0
  interface: eno2
  ip_method: dhcp
  ip_address: 192.168.50.10/24
  gateway: 192.168.50.1
  dns: 8.8.8.8

base_templates:
  - name: alma85_base
    os: alma8.5
    disk_size: 20G
    disk_path: "{{ template_images_dir }}/alma85_base.qcow2"
    root_password: "{{ default_password }}"
  - name: alma9_base
    os: alma9
    disk_size: 20G
    disk_path: "{{ template_images_dir }}/alma9_base.qcow2"
    root_password: "{{ default_password }}"
    iso_path: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2

vm_instances:
  - name: "bastion"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/bastion.qcow2"
    disk_size: 50G
    memory_mb: 4096
    network: br0
    vcpus: 2
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true

  - name: "master1"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/master1.qcow2"
    disk_size: 100G
    network: br0
    memory_mb: 8196
    vcpus: 4
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true

  - name: "master2"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/master2.qcow2"
    disk_size: 100G
    network: br0
    memory_mb: 8196
    vcpus: 4
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true

  - name: "master3"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/master3.qcow2"
    disk_size: 100G
    network: br0
    memory_mb: 8196
    vcpus: 4
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true

  - name: "worker1"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/worker1.qcow2"
    disk_size: 100G
    network: br0
    memory_mb: 8196
    vcpus: 4
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true

  - name: "worker2"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/worker2.qcow2"
    disk_size: 100G
    network: br0
    memory_mb: 8196
    vcpus: 4
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true

  - name: "worker3"
    base_path: "{{ template_images_dir }}/alma9_base.qcow2"
    disk_path: "{{ vm_images_dir }}/worker3.qcow2"
    disk_size: 100G
    network: br0
    memory_mb: 8196
    vcpus: 4
    root_password: "{{ default_password }}"
    ssh_authorized_key: "{{ default_ssh_public_key }}"
    enable_autostart: true
