---
all:
  children:
    kvm_hosts:
      hosts:
        host1:
          ansible_host: 192.168.80.241

    bastion:
      hosts:
        bastion1:
          ansible_host: 192.168.80.214

    server:
      hosts:
        master1-1:
          ansible_host: 192.168.80.238
        master1-2:
          ansible_host: 192.168.80.233
        master1-3:
          ansible_host: 192.168.80.232

    agent:
      hosts:
        worker1-1:
          ansible_host: 192.168.80.213
        worker1-2:
          ansible_host: 192.168.80.221
        worker1-3:
          ansible_host: 192.168.80.209

