---
all:
  children:
    kvm_hosts:
      hosts:
        host1:
          ansible_host: 192.168.80.241
        host2:
          ansible_host: 192.168.80.242

    bastion:
      hosts:
        bastion1:
          ansible_host: 192.168.80.214
        bastion2:
          ansible_host: 192.168.80.215

  vars:
    ansible_user: ansible