---
kvm_hosts:
  hosts:
    host1:
      ansible_host: 100.109.18.70
      ansible_user: ansible
      ansible_become: true
      ansible_become_user: root

bastion:
  hosts:
    bastion1:
      ansible_host: 192.168.50.20

all:
  vars:
    ansible_user: ansible
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p ansible@100.109.18.70"'

virt_hosts:
  vars:
    ansible_ssh_common_args: ''