---
kvm_hosts:
  hosts:
    host1:
      ansible_host: 100.109.18.70
      ansible_user: ansible
      ansible_become: true
      ansible_become_user: root

bastion:
  hosts:
    bastion:
      ansible_host: 192.168.50.38
k3s_cluster:
  children:
    server:
      hosts:
        master1:
          ansible_host: 192.168.50.39
        master2:
          ansible_host: 192.168.50.40
        master3:
          ansible_host: 192.168.50.41

    agent:
      hosts:
        worker1:
          ansible_host: 192.168.50.42
        worker2:
          ansible_host: 192.168.50.43
        worker3:
          ansible_host: 192.168.50.44

all:
  vars:
    ansible_user: ansible
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p ansible@100.109.18.70"'

kvm_hosts:
  vars:
    ansible_ssh_common_args: ''
