---
all:
  children:
    proxmox_hosts:
      hosts:
        host1:
          ansible_host: 192.168.80.21
        host2:
          ansible_host: 192.168.80.22
        host3:
          ansible_host: 192.168.80.23

    bastion:
      hosts:
        bastion1:
          ansible_host: 192.168.80.51
        bastion2:
          ansible_host: 192.168.80.52
        bastion3:
          ansible_host: 192.168.80.53

  vars:
    ansible_user: ansible