---
all:
  children:
    kvm_hosts:
      hosts:
        host1:
          ansible_host: 192.168.80.241
        host2:
          ansible_host: 192.168.80.242

    bastion:
      hosts:
        bastion1:
          ansible_host: 192.168.80.214
        bastion2:
          ansible_host: 192.168.80.215

    server:
      hosts:
        master1-1:
          ansible_host: 192.168.80.238
        master1-2:
          ansible_host: 192.168.80.233
        master1-3:
          ansible_host: 192.168.80.232
        master2-1:
          ansible_host: 192.168.80.228
        master2-2:
          ansible_host: 192.168.80.227
        master2-3:
          ansible_host: 192.168.80.226

    agent:
      hosts:
        worker1-1:
          ansible_host: 192.168.80.213
        worker1-2:
          ansible_host: 192.168.80.221
        worker1-3:
          ansible_host: 192.168.80.209
        worker2-1:
          ansible_host: 192.168.80.219
        worker2-2:
          ansible_host: 192.168.80.218
        worker2-3:
          ansible_host: 192.168.80.217
    
    k3s_cluster:
      children:
        server:
        agent: