---
all:
  children:
    cluster2_server:
      hosts:
        master2-1:
          ansible_host: 192.168.80.228
        master2-2:
          ansible_host: 192.168.80.227
        master2-3:
          ansible_host: 192.168.80.226

    cluster2_agent:
      hosts:
        worker2-1:
          ansible_host: 192.168.80.219
        worker2-2:
          ansible_host: 192.168.80.218
        worker2-3:
          ansible_host: 192.168.80.217
    
    server:
      children:
        cluster2_server:
    
    agent:
      children:
        cluster2_agent:
    
    k3s_cluster:
      children:
        server:
        agent:

  vars:
    ansible_user: ansible