---
k3s_version: v1.30.2+k3s1
token: "{{ lookup('amazon.aws.aws_ssm', '/k3s/token', region='us-east-2' ) }}"
api_port: 6443
k3s_etcd_db_username: "{{ lookup('amazon.aws.aws_ssm', '/k3s/db_username', region='us-east-2' }}"
k3s_etcd_db_password: "{{ lookup('amazon.aws.aws_ssm', '/k3s/db_password', region='us-east-2' }}"
k3s_etcd_db_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/k3s/db_endpoint', region='us-east-2' }}"

api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
cluster_context: skylab-cluster1

# Cluster 1 specific networking
extra_server_args: >-
  --cluster-domain cluster1.skylarhoughtongithub.local

extra_agent_args: >-
  --node-label cluster=skylab-cluster1
  --node-label environment=lab
  --kubelet-arg max-pods=250
  --kubelet-arg cluster-domain=cluster1.skylarhoughtongithub.local

server_config_yaml: |
  cluster-cidr: "10.100.0.0/16"
  service-cidr: "10.110.0.0/16"
  cluster-dns: "10.110.0.10"
  cluster-domain: "cluster1.skylarhoughtongithub.local"
  
  # Security
  secrets-encryption: true
  
  # Node labels for masters
  node-label:
    - "cluster=skylab-cluster1"
    - "node-type=master"
    - "workload-type=control-plane"
    - "environment=lab"

agent_config_yaml: |
  node-label:
    - "cluster=skylab-cluster1"
    - "node-type=worker"
    - "workload-type=general"
    - "environment=lab"
  
  # Kubelet configuration
  kubelet-arg:
    - "max-pods=250"
    - "cluster-dns=10.110.0.10"
    - "cluster-domain=cluster1.skylarhoughtongithub.local"

# External etcd configuration
etcd_cluster1_endpoint: "postgres://{{ k3s_etcd_db_username }}:{{ k3s_etcd_db_password }}@{{ k3s_etcd_db_endpoint }}:5432/k3s_cluster1?sslmode=require"
