---
# defaults file for kvm

kvm_packages:
  - bridge-utils
  - cockpit
  - cockpit-machines
  - cockpit-podman
  - cockpit-system
  - libguestfs-tools
  - libvirt
  - libvirt-client
  - libvirt-daemon
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-storage
  - NetworkManager
  - NetworkManager-libnm
  - qemu-kvm
  - virt-install
  - virt-manager
  - virt-top
  - virt-viewer
