#SPDX-License-Identifier: MIT-0
---
# defaults file for okd_bind
bind_defaults:
  domain: example.com
  subnet: 192.168.0
  okd_subnet: 192.168.00.0/24
  serial: "{{ '%Y%m%d00' | strftime }}"
  dns_forwarders:
    - 8.8.8.8
    - 8.8.4.4
  nodes:
    bootstrap:
      name: bootstrap
      ip: OKD4_BOOTSTRAP_SERVER_IP
    control_plane:
      - name: master-0
        ip: OKD4_MASTER_0_SERVER_IP
      - name: master-1
        ip: OKD4_MASTER_1_SERVER_IP
      - name: master-2
        ip: OKD4_MASTER_2_SERVER_IP
    compute:
      - name: worker-0
        ip: OKD4_WORKER_0_SERVER_IP
      - name: worker-1
        ip: OKD4_WORKER_1_SERVER_IP
    infra:
      - name: infra-0
        ip: OKD4_INFRA_0_SERVER_IP
      - name: infra-1
        ip: OKD4_INFRA_1_SERVER_IP