#SPDX-License-Identifier: MIT-0
---
# handlers file for kvm

- name: restart network
  service:
    name: network
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  when: use_firewalld | bool