---
all:
  children:
    server:
      hosts:
        master2-1:
          ansible_host: 192.168.80.201
        master2-2:
          ansible_host: 192.168.80.202
        master2-3:
          ansible_host: 192.168.80.203

    agent:
      hosts:
        worker2-1:
          ansible_host: 192.168.80.211
        worker2-2:
          ansible_host: 192.168.80.212
        worker2-3:
          ansible_host: 192.168.80.213
    
    k3s_cluster:
      children:
        server:
        agent:

  vars:
    ansible_user: ansible