#SPDX-License-Identifier: MIT-0
---
# tasks file for proxmox_init
- name: install essential packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - vim
      - htop
      - iotop
      - git
      - unzip
      - rsync
      - tmux
      - tcpdump
      - iperf3
      - smartmontools
      - pciutils
      - usbutils
      - tree
      - jq
      - bc
      - dnsutils
      - net-tools
    state: present

- name: Clone and install pve-nag-buster
  ansible.builtin.shell: |
    git clone https://github.com/foundObjects/pve-nag-buster.git /tmp/pve-nag-buster
    cd /tmp/pve-nag-buster
    sudo ./install.sh
  args:
    creates: /tmp/pve-nag-buster

- name: Add Proxmox no-subscription repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-no-subscription.list
    line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    create: yes
    backup: yes
  notify: update apt cache

- name: Remove Ceph enterprise repository if it exists
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb https://enterprise.proxmox.com'
    line: '# deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
    backup: yes
  ignore_errors: yes
  notify: update apt cache

- name: Add Ceph no-subscription repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    line: 'deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription'
    create: yes
    backup: yes
  notify: update apt cache

- name: Set up custom MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/update-motd.d/00-skylab
    mode: '0755'
