---
- name: install haproxy
  hosts: node
  become: true
  remote_user: ansible
  tasks:
  - name: cron log
    cron:
      name: logger
      minute: "15"
      hour: "*/1"
      job: logger "echo time!"
      state: present
  - name: Install the 'Gnome desktop' environment group
    ansible.builtin.yum:
      name: "@^gnome-desktop-environment"
      state: present
  - command: systemctl set-default graphical.target
  - name: Set DNS before reboot
    cron:
      name: set-dns
      special_time: reboot
      job: echo "8.8.8.8" > /etc/resolve.conf
  - name: at system time
    at:
      command: date
      count: 5
      units: minutes
      state: true
    with_sequence: count=5

