---
- name: Install docker
  hosts: all
  remote_user: shoutsky
  become: true
  roles:
  - name: ../../roles/init_linux
    tags: ["init"]

  - name: ../../roles/docker_setup_host
    tags: ["docker"]

