- name: Install httpd deps
  yum:
    name:
     - httpd
     - mod_ssl
     - php
    state: present

- name: Start/enable httpd
  service:
    name: httpd
    state: present
    enabled: True

- name: open firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
   - http
   - https

- name: configure httpd
  template:
    src: template/index.html.j2
    dest: /var/www/html/index.html
    mode: 0755
  notify: restart httpd

    
    