---
all:
  children:
    server:
      hosts:
        master1-1:
          ansible_host: 192.168.80.101
        master1-2:
          ansible_host: 192.168.80.102
        master1-3:
          ansible_host: 192.168.80.103

    agent:
      hosts:
        worker1-1:
          ansible_host: 192.168.80.111
        worker1-2:
          ansible_host: 192.168.80.112
        worker1-3:
          ansible_host: 192.168.80.113
    
    k3s_cluster:
      children:
        server:
        agent:

  vars:
    ansible_user: ansible