#SPDX-License-Identifier: MIT-0
---
# tasks file for kvm_setup_bridge
- name: Include bridge setup tasks
  include_tasks: bridge_setup.yml

- name: Include libvirt setup tasks
  include_tasks: libvirt_setup.yml
  when: bridge_configuration.create
