---
- name: Set up KVM infrastructure
  hosts: kvm_hosts
  become: true
  roles:
  - name: ../../roles/kvm_setup_host
    tags: ["host"]

- name: KVM Environment Init 
  import_playbook: ../init/linux.yml
  tags: ["init"]