---
- name: Set up KVM infrastructure
  hosts: virt_hosts
  become: true
  vars:
    create_nat_network: true
  roles:
  - ../../roles/kvm_setup_host

- name: KVM Environment Init 
  import_playbook: ../init_linux_instance/linux_init.yml