---
k3s_version: v1.30.2+k3s1
token: "{{ lookup('amazon.aws.aws_ssm', '/k3s/token', region='us-east-2' ) }}"
api_port: 6443
k3s_etcd_db_username: "{{ lookup('amazon.aws.aws_ssm', '/k3s/db_username', region='us-east-2' }}"
k3s_etcd_db_password: "{{ lookup('amazon.aws.aws_ssm', '/k3s/db_password', region='us-east-2' }}"
k3s_etcd_db_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/k3s/db_endpoint', region='us-east-2' }}"

api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

cluster_context: skylab-cluster2

# Cluster 2 specific networking
extra_server_args: >-
  --cluster-domain cluster2.skylarhoughtongithub.local
  --node-taint=node-role.kubernetes.io/control-plane:PreferNoSchedule

extra_agent_args: >-
  --node-label cluster=skylab-cluster2
  --node-label environment=lab
  --kubelet-arg max-pods=250
  --kubelet-arg cluster-domain=cluster2.skylarhoughtongithub..local

server_config_yaml: |
  # Cluster 2 networking - different CIDRs to avoid conflicts
  cluster-cidr: "10.200.0.0/16"
  service-cidr: "10.210.0.0/16"
  cluster-dns: "10.210.0.10"
  cluster-domain: "cluster2.skylarhoughtongithub.local"
  
  # Security
  secrets-encryption: true
  
  # Node labels for masters
  node-label:
    - "cluster=skylab-cluster2"
    - "node-type=master"
    - "node-role=control-plane"
    - "environment=lab"

agent_config_yaml: |
  node-label:
    - "cluster=skylab-cluster2"
    - "node-type=worker"
    - "workload-type=general"
    - "environment=lab"
  
  # Kubelet configuration
  kubelet-arg:
    - "max-pods=250"
    - "cluster-dns=10.210.0.10"
    - "cluster-domain=cluster2.skylarhoughtongithub.local"

# External etcd configuration
etcd_cluster2_endpoint: "postgres://{{ k3s_etcd_db_username }}:{{ k3s_etcd_db_password }}@{{ k3s_etcd_db_endpoint }}:5432/k3s_cluster2?sslmode=require"

