---
# defaults file for kvm

kvm_packages:
  - libguestfs-tools
  - guestfs-tools
  - libvirt
  - libvirt-client
  - libvirt-daemon
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-storage
  - qemu-kvm
  - virt-install
  - virt-manager
  - virt-top
  - virt-viewer

install_kvm: true

# Bridge packages
bridge_packages:
  - bridge-utils
  - NetworkManager-libnm

# Bridge network settings
create_nat_network: false
nat_network_name: "openshift4"
nat_network_address: "192.168.100.1"  # Change to your desired IP
nat_network_cidr: "255.255.255.0"  # Change to your desired IP

# Firewall settings
use_firewalld: false       # Set to false if not using firewalld
