#SPDX-License-Identifier: MIT-0
---
# tasks file for okd_nginx_kernel_boot    
- name: Install nginx and SSL dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - openssl

- name: Ensure nginx service is enabled and started
  service:
    name: nginx
    state: started
    enabled: yes