#SPDX-License-Identifier: MIT-0
---
# tasks file for okd_bind
- name: merge override and default parameters
  ansible.builtin.set_fact:
    bind_configuration: "{{ bind_defaults | combine(okd_bastion_configuration | default({}), recursive=true) }}"

- name: Configure named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'
    backup: yes
  notify: Restart Bind

- name: Create named directory
  ansible.builtin.file:
    path: /etc/named
    state: directory
    owner: root
    group: named
    mode: '0750'

- name: Configure named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/named/named.conf.local
    owner: root
    group: named
    mode: '0640'
    backup: yes
  notify: Restart Bind

- name: Create zones directory
  ansible.builtin.file:
    path: /var/named/zones
    state: directory
    owner: named
    group: named
    mode: '0770'

- name: Configure forward zone file
  ansible.builtin.template:
    src: db.domain.j2
    dest: "/var/named/zones/db.{{ okd_bastion_configuration.domain }}"
    owner: named
    group: named
    mode: '0640'
    backup: yes
  notify: Restart Bind

- name: Configure reverse zone file
  ansible.builtin.template:
    src: db.reverse.j2
    dest: "/var/named/zones/db.{{ okd_bastion_configuration.subnet }}"
    owner: named
    group: named
    mode: '0640'
    backup: yes
  notify: Restart Bind

- name: Start and enable Bind service
  ansible.builtin.service:
    name: named
    state: started
    enabled: yes
