---

#
# Kubeinit secrets data
#

###
# This variable contains,
# a secret placeholder.
kubeinit_secrets_secret:
  ###
  # The secret name represents
  # a secret placeholder.
  secret_name: kubeinit-secrets
  ###
  # The envvar name works for
  # a secret placeholder.
  envvar_name: KUBEINIT_SECRETS

#
# Nested comments in lists aren't supported yet.
#

###
# All the secrets will enable
# the deployment capabilities, this is
# a docs placeholder.
#
# .. code-block:: yaml
#
#    kubeinit_secrets:
#      - secret_name: This is the secret name.
#        dict_varname: Where we will store the secret.
#        dict_key: The secret value.
#        env_varname: A default value from an environmental variable.
#
# The ones that are currently used:
#
# - kubeinit-ssh-key: Docs placeholder.
# - dockerhub-username: Docs placeholder.
# - dockerhub-password: Docs placeholder.
# - openshift-pullsecret: Docs placeholder.
kubeinit_secrets:
  - secret_name: kubeinit-ssh-key
    dict_varname: kubeinit
    dict_key: ssh_key
    envvar_name: KUBEINIT_SECRET_SSH_KEY
  - secret_name: dockerhub-username
    dict_varname: dockerhub
    dict_key: username
    envvar_name: KUBEINIT_SECRET_DOCKER_USERNAME
  - secret_name: dockerhub-password
    dict_varname: dockerhub
    dict_key: password
    envvar_name: KUBEINIT_SECRET_DOCKER_PASSWORD
  - secret_name: openshift-pullsecret
    dict_varname: openshift
    dict_key: pullsecret
    envvar_name: KUBEINIT_SECRET_OPENSHIFT_PULLSECRET
