---
k3s_version: v1.30.2+k3s1
token: "{{ lookup('amazon.aws.aws_ssm', '/k3s/token', region='us-east-2' ) }}"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

# Optional vars
# extra_server_args: ""
# extra_agent_args: ""
# cluster_context: k3s-ansible
# api_port: 6443
# k3s_server_location: /var/lib/rancher/k3s
# systemd_dir: /etc/systemd/system
# extra_service_envs: [ 'ENV_VAR1=VALUE1', 'ENV_VAR2=VALUE2' ]
# user_kubectl: true, by default kubectl is symlinked and configured for use by ansible_user. Set to false to only kubectl via root user.
# server_config_yaml:  |
#   This is now an inner yaml file. Maintain the indentation.
#   YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
#   See https://docs.k3s.io/installation/configuration#configuration-file
# agent_config_yaml:  |
#   Same as server_config_yaml, but for the agent nodes.
#   YAML here will be placed as the content of /etc/rancher/k3s/config.yaml
#   See https://docs.k3s.io/installation/configuration#configuration-file
# registries_config_yaml:  |
#   Containerd can be configured to connect to private registries and use them to pull images as needed by the kubelet.
#   YAML here will be placed as the content of /etc/rancher/k3s/registries.yaml
#   See https://docs.k3s.io/installation/private-registry